import type { AppSettings, IndicatorDescriptor, MarketSymbol, SupportedTimeframe } from '../types/market'
import { APP_ENV } from '../utils/env'

export const STORAGE_KEYS = {
  watchlist: 'fa.watchlist',
  settings: 'fa.settings',
  alerts: 'fa.alerts',
  enabledIndicators: 'fa.enabledIndicators',
  enabledGroups: 'fa.enabledGroups',
  indicatorDefaultsMigrated: 'fa.indicatorDefaultsMigrated',
} as const

export const DEFAULT_SETTINGS: AppSettings = {
  finnhubKey: APP_ENV.finnhubKey,
  alphaVantageKey: APP_ENV.alphaVantageKey,
  openAiKey: APP_ENV.openAiKey,
  openAiModel: APP_ENV.openAiModel,
  theme: APP_ENV.theme,
  multiChartCount: APP_ENV.multiChartCount,
}

export const TIMEFRAMES: SupportedTimeframe[] = [
  '5m',
  '15m',
  '30m',
  '1h',
  '2h',
  '4h',
  '1D',
  '1W',
  '2W',
  '1M',
  '2M',
  '3M',
  '6M',
  '1Y',
  '2Y',
  '3Y',
]

export const SIGNAL_MATRIX_TIMEFRAMES: SupportedTimeframe[] = [
  '5m',
  '15m',
  '30m',
  '1h',
  '4h',
  '1D',
  '1W',
  '1M',
  '3M',
  '1Y',
]

export const DEFAULT_WATCHLIST = ['BTCUSD', 'ETHUSD', 'XAUUSD', 'EURUSD', 'VCB', 'HPG']

export const MARKETS: MarketSymbol[] = [
  {
    id: 'XAUUSD',
    label: 'Vàng XAU/USD',
    category: 'commodity',
    yahooSymbol: 'GC=F',
    finnhubSymbol: 'OANDA:XAU_USD',
    precision: 2,
  },
  {
    id: 'XAGUSD',
    label: 'Bạc XAG/USD',
    category: 'commodity',
    yahooSymbol: 'SI=F',
    finnhubSymbol: 'OANDA:XAG_USD',
    precision: 3,
  },
  {
    id: 'USOIL',
    label: 'Dầu WTI',
    category: 'commodity',
    yahooSymbol: 'CL=F',
    precision: 2,
  },
  {
    id: 'BRENT',
    label: 'Dầu Brent',
    category: 'commodity',
    yahooSymbol: 'BZ=F',
    precision: 2,
  },
  {
    id: 'BTCUSD',
    label: 'Bitcoin',
    category: 'crypto',
    yahooSymbol: 'BTC-USD',
    binanceSymbol: 'btcusdt',
    precision: 2,
  },
  {
    id: 'ETHUSD',
    label: 'Ethereum',
    category: 'crypto',
    yahooSymbol: 'ETH-USD',
    binanceSymbol: 'ethusdt',
    precision: 2,
  },
  {
    id: 'EURUSD',
    label: 'EUR/USD',
    category: 'forex',
    yahooSymbol: 'EURUSD=X',
    finnhubSymbol: 'OANDA:EUR_USD',
    precision: 5,
  },
  {
    id: 'GBPUSD',
    label: 'GBP/USD',
    category: 'forex',
    yahooSymbol: 'GBPUSD=X',
    finnhubSymbol: 'OANDA:GBP_USD',
    precision: 5,
  },
  {
    id: 'VNINDEX',
    label: 'VN-Index',
    category: 'index',
    yahooSymbol: '^VNINDEX',
    precision: 2,
  },
  {
    id: 'SP500',
    label: 'S&P 500',
    category: 'index',
    yahooSymbol: '^GSPC',
    precision: 2,
  },
  {
    id: 'NASDAQ',
    label: 'Nasdaq',
    category: 'index',
    yahooSymbol: '^IXIC',
    precision: 2,
  },
  {
    id: 'DOWJONES',
    label: 'Dow Jones',
    category: 'index',
    yahooSymbol: '^DJI',
    precision: 2,
  },
  {
    id: 'VCB',
    label: 'Vietcombank',
    category: 'stock',
    yahooSymbol: 'VCB.VN',
    precision: 2,
  },
  {
    id: 'VIC',
    label: 'Vingroup',
    category: 'stock',
    yahooSymbol: 'VIC.VN',
    precision: 2,
  },
  {
    id: 'HPG',
    label: 'Hòa Phát',
    category: 'stock',
    yahooSymbol: 'HPG.VN',
    precision: 2,
  },
  {
    id: 'FPT',
    label: 'FPT',
    category: 'stock',
    yahooSymbol: 'FPT.VN',
    precision: 2,
  },
]

export const INDICATORS: IndicatorDescriptor[] = [
  { key: 'sma20', label: 'SMA 20', group: 'trend', overlay: true },
  { key: 'sma50', label: 'SMA 50', group: 'trend', overlay: true },
  { key: 'sma100', label: 'SMA 100', group: 'trend', overlay: true },
  { key: 'sma200', label: 'SMA 200', group: 'trend', overlay: true },
  { key: 'ema9', label: 'EMA 9', group: 'trend', overlay: true },
  { key: 'ema21', label: 'EMA 21', group: 'trend', overlay: true },
  { key: 'dema20', label: 'DEMA 20', group: 'trend', overlay: true },
  { key: 'tema20', label: 'TEMA 20', group: 'trend', overlay: true },
  { key: 'wma20', label: 'WMA 20', group: 'trend', overlay: true },
  { key: 'hma20', label: 'HMA 20', group: 'trend', overlay: true },
  { key: 'vwap', label: 'VWAP', group: 'trend', overlay: true },
  { key: 'bollinger', label: 'Dải Bollinger', group: 'trend', overlay: true },
  { key: 'keltner', label: 'Kênh Keltner', group: 'trend', overlay: true },
  { key: 'donchian', label: 'Kênh Donchian', group: 'trend', overlay: true },
  { key: 'ichimoku', label: 'Ichimoku', group: 'trend', overlay: true },
  { key: 'psar', label: 'Parabolic SAR', group: 'trend', overlay: true },
  { key: 'adx', label: 'ADX', group: 'trend', overlay: false },
  { key: 'rsi', label: 'RSI', group: 'momentum', overlay: false },
  { key: 'macd', label: 'MACD', group: 'momentum', overlay: false },
  { key: 'stoch', label: 'Stochastic', group: 'momentum', overlay: false },
  { key: 'stochRsi', label: 'Stoch RSI', group: 'momentum', overlay: false },
  { key: 'cci', label: 'CCI', group: 'momentum', overlay: false },
  { key: 'williamsR', label: 'Williams %R', group: 'momentum', overlay: false },
  { key: 'roc', label: 'ROC', group: 'momentum', overlay: false },
  { key: 'momentum', label: 'Momentum', group: 'momentum', overlay: false },
  { key: 'ultimate', label: 'Dao động Ultimate', group: 'momentum', overlay: false },
  { key: 'atr', label: 'ATR', group: 'volatility', overlay: false },
  { key: 'sd20', label: 'Độ lệch chuẩn 20', group: 'volatility', overlay: false },
  { key: 'hv20', label: 'Biến động lịch sử', group: 'volatility', overlay: false },
  { key: 'obv', label: 'OBV', group: 'volume', overlay: false },
  { key: 'cmf', label: 'CMF', group: 'volume', overlay: false },
  { key: 'mfi', label: 'MFI', group: 'volume', overlay: false },
  { key: 'volumeSma20', label: 'SMA khối lượng 20', group: 'volume', overlay: false },
  { key: 'forceIndex', label: 'Chỉ số lực', group: 'volume', overlay: false },
  { key: 'vwma20', label: 'VWMA 20', group: 'volume', overlay: true },
  { key: 'pivot', label: 'Điểm pivot', group: 'support', overlay: true },
  { key: 'fibonacci', label: 'Fibonacci', group: 'support', overlay: true },
  { key: 'doji', label: 'Doji', group: 'pattern', overlay: false },
  { key: 'engulfing', label: 'Nhấn chìm', group: 'pattern', overlay: false },
  { key: 'hammer', label: 'Búa / Sao băng', group: 'pattern', overlay: false },
  { key: 'supertrend', label: 'Supertrend', group: 'advanced', overlay: true },
  { key: 'aroon', label: 'Dao động Aroon', group: 'advanced', overlay: false },
  { key: 'cmo', label: 'CMO', group: 'advanced', overlay: false },
  { key: 'trix', label: 'TRIX', group: 'advanced', overlay: false },
  { key: 'elderRay', label: 'Elder Ray', group: 'advanced', overlay: false },
  { key: 'dpo', label: 'DPO', group: 'advanced', overlay: false },
  { key: 'guppy', label: 'Guppy MMA', group: 'advanced', overlay: true },
]

export const PRESETS = {
  scalping: ['rsi', 'stoch', 'ema9', 'ema21'],
  swing: ['macd', 'adx', 'ichimoku'],
  longTerm: ['sma50', 'sma200', 'supertrend'],
} as const
